[package]
name = "generate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
quote = "1.0.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"

